source 'https://rubygems.org'

gem 'sinatra', '~> 2.0'
gem 'tracker_api', '~> 1.10'
gem 'octokit', '~> 4.0'
gem 'jira-ruby', '~> 2.0'
gem 'config', '~> 2.2'
gem 'activesupport', '~>5.0'
gem 'rest-client', '~>2.1'
gem 'parallel', '~>1.19'
